### ISSUE TITLE
Frage: Kompatibilität mit der aktuellen Woltlab Suite 5.4?

### ISSUE THREAD

**Issue by IAmSamp** [derpierre65/pWBB4#3]
Hay,

ich wollte mal kurz fragen da hier lange kein Update mehr kam ob die aktuelle Version ebenfalls mit der aktuellen Woltlab Suite 5.4 kompatibel ist und falls nicht ob ein Update hierfür geplant ist?
Wirklich das Plugin von dir ist einfach unschlagbar und sorgt für eine traumhafte Integration der Woltlab Suite mit einem SAMP-Server.
Vielen Dank für dein Engagement und dass du das Projekt kostenlos zur Verfügung stellst.

MfG IAmSamp

**Comment by derpierre65** [comment]
ich habe keine lizenz für die 5.x version und kann es daher selbst nicht testen
schon mal mit einer test installation getestet?

theoretisch nutze ich direkt die woltlab funktionen, die müssten eig. in den neueren versionen weiterhin funktionieren, der große breaking change war von 4 auf 5
